let itemList = [
    {
        itemId: "LABEL_SI_STUDY_IDENTIFICATION",
        itemLabel: "Study Identification",
        elementId: "C.5",
        notation: "",
        uiType: "LABEL",
        dataType: "",
        maxLength: "",
        card: "0..1",
        dataLimit: "",
        dataSource: "",
        codeList: null,
        nullFlavorList: null
    },
    {
        itemId: "LABEL_SI_STUDY_REGISTRATION",
        itemLabel: "Study Registration (repeat as necessary)",
        elementId: "C.5.1.r",
        notation: "",
        uiType: "LABEL",
        dataType: "",
        maxLength: "",
        card: "0..N",
        dataLimit: "",
        dataSource: "",
        codeList: null,
        nullFlavorList: null
    },
    {
        itemId: "STD_NAME",
        itemLabel: "研究名称",
        elementId: "C.5.2",
        notation: "Y",
        uiType: "TEXT_AREA",
        dataType: "AN",
        maxLength: "2000",
        card: "0..1",
        dataLimit: "",
        dataSource: "",
        codeList: null,
        nullFlavorList: [
            { codeValue: "[[ASKU]]", codeLabel: "Asked But Unknown" },
            { codeValue: "[[NASK]]", codeLabel: "Not Asked" }
        ]
    },
    {
        itemId: "STD_REACTION_TYPE",
        itemLabel: "该反应/事件的研究类型",
        elementId: "C.5.4",
        notation: "",
        uiType: "RADIO",
        dataType: "N",
        maxLength: "1",
        card: "0..1",
        dataLimit: "",
        dataSource: "CODE",
        codeList: [
            { codeValue: "1", codeLabel: "临床试验" },
            {
                codeValue: "2",
                codeLabel:
                    "个例患者使用个例患者使用（例如“同情使用同情使用”或“指定患者用途”）"
            },
            {
                codeValue: "3",
                codeLabel:
                    "其他研究（例如药物流行病学、药物经济学、重点监测重点）"
            }
        ],
        nullFlavorList: null
    },
    {
        itemId: "STD_REG_COUNTRY",
        itemLabel: "研究注册国家",
        elementId: "C.5.1.r.2",
        notation: "",
        uiType: "AUTOCOMPLETE",
        dataType: "A",
        maxLength: "2",
        card: "0..1",
        dataLimit: "",
        dataSource: "CODE",
        codeList: [
            { codeValue: "AD", codeLabel: "Andorra" },
            { codeValue: "AE", codeLabel: "United Arab Emirates" },
            { codeValue: "AF", codeLabel: "Afghanistan" },
            { codeValue: "AG", codeLabel: "Antigua and Barbuda" },
            { codeValue: "AI", codeLabel: "Anguilla" },
            { codeValue: "AL", codeLabel: "Albania" },
            { codeValue: "AM", codeLabel: "Armenia" },
            { codeValue: "AO", codeLabel: "Angola" },
            { codeValue: "AQ", codeLabel: "Antarctica" },
            { codeValue: "AR", codeLabel: "Argentina" },
            { codeValue: "AS", codeLabel: "American Samoa" },
            { codeValue: "AT", codeLabel: "Austria" },
            { codeValue: "AU", codeLabel: "Australia" },
            { codeValue: "AW", codeLabel: "Aruba" },
            { codeValue: "AX", codeLabel: "Aland Islands" },
            { codeValue: "AZ", codeLabel: "Azerbaijan" },
            { codeValue: "BA", codeLabel: "Bosnia and Herzegovina" },
            { codeValue: "BB", codeLabel: "Barbados" },
            { codeValue: "BD", codeLabel: "Bangladesh" },
            { codeValue: "BE", codeLabel: "Belgium" },
            { codeValue: "BF", codeLabel: "Burkina Faso" },
            { codeValue: "BG", codeLabel: "Bulgaria" },
            { codeValue: "BH", codeLabel: "Bahrain" },
            { codeValue: "BI", codeLabel: "Burundi" },
            { codeValue: "BJ", codeLabel: "Benin" },
            { codeValue: "BL", codeLabel: "Saint Barthelemy" },
            { codeValue: "BM", codeLabel: "Bermuda" },
            { codeValue: "BN", codeLabel: "Brunei Darussalam" },
            { codeValue: "BO", codeLabel: "Bolivia (Plurinational State of)" },
            { codeValue: "BQ", codeLabel: "Bonaire, Sint Eustatius and Saba" },
            { codeValue: "BR", codeLabel: "Brazil" },
            { codeValue: "BS", codeLabel: "Bahamas" },
            { codeValue: "BT", codeLabel: "Bhutan" },
            { codeValue: "BV", codeLabel: "Bouvet Island" },
            { codeValue: "BW", codeLabel: "Botswana" },
            { codeValue: "BY", codeLabel: "Belarus" },
            { codeValue: "BZ", codeLabel: "Belize" },
            { codeValue: "CA", codeLabel: "Canada" },
            { codeValue: "CC", codeLabel: "Cocos (Keeling) Islands" },
            {
                codeValue: "CD",
                codeLabel: "Congo (Democratic Republic of the)"
            },
            { codeValue: "CF", codeLabel: "Central African Republic" },
            { codeValue: "CG", codeLabel: "Congo" },
            { codeValue: "CH", codeLabel: "Switzerland" },
            { codeValue: "CI", codeLabel: "Cote d'Ivoire" },
            { codeValue: "CK", codeLabel: "Cook Islands" },
            { codeValue: "CL", codeLabel: "Chile" },
            { codeValue: "CM", codeLabel: "Cameroon" },
            { codeValue: "CN", codeLabel: "China" },
            { codeValue: "CO", codeLabel: "Colombia" },
            { codeValue: "CR", codeLabel: "Costa Rica" },
            { codeValue: "CU", codeLabel: "Cuba" },
            { codeValue: "CV", codeLabel: "Cabo Verde" },
            { codeValue: "CW", codeLabel: "Curacao" },
            { codeValue: "CX", codeLabel: "Christmas Island" },
            { codeValue: "CY", codeLabel: "Cyprus" },
            { codeValue: "CZ", codeLabel: "Czechia" },
            { codeValue: "DE", codeLabel: "Germany" },
            { codeValue: "DJ", codeLabel: "Djibouti" },
            { codeValue: "DK", codeLabel: "Denmark" },
            { codeValue: "DM", codeLabel: "Dominica" },
            { codeValue: "DO", codeLabel: "Dominican Republic" },
            { codeValue: "DZ", codeLabel: "Algeria" },
            { codeValue: "EC", codeLabel: "Ecuador" },
            { codeValue: "EE", codeLabel: "Estonia" },
            { codeValue: "EG", codeLabel: "Egypt" },
            { codeValue: "EH", codeLabel: "Western Sahara" },
            { codeValue: "ER", codeLabel: "Eritrea" },
            { codeValue: "ES", codeLabel: "Spain" },
            { codeValue: "ET", codeLabel: "Ethiopia" },
            { codeValue: "EU", codeLabel: "European Union" },
            { codeValue: "FI", codeLabel: "Finland" },
            { codeValue: "FJ", codeLabel: "Fiji" },
            { codeValue: "FK", codeLabel: "Falkland Islands (Malvinas)" },
            { codeValue: "FM", codeLabel: "Micronesia (Federated States of)" },
            { codeValue: "FO", codeLabel: "Faroe Islands" },
            { codeValue: "FR", codeLabel: "France" },
            { codeValue: "GA", codeLabel: "Gabon" },
            {
                codeValue: "GB",
                codeLabel: "United Kingdom of Great Britain and Northern Ireland"
            },
            { codeValue: "GD", codeLabel: "Grenada" },
            { codeValue: "GE", codeLabel: "Georgia" },
            { codeValue: "GF", codeLabel: "French Guiana" },
            { codeValue: "GG", codeLabel: "Guernsey" },
            { codeValue: "GH", codeLabel: "Ghana" },
            { codeValue: "GI", codeLabel: "Gibraltar" },
            { codeValue: "GL", codeLabel: "Greenland" },
            { codeValue: "GM", codeLabel: "Gambia" },
            { codeValue: "GN", codeLabel: "Guinea" },
            { codeValue: "GP", codeLabel: "Guadeloupe" },
            { codeValue: "GQ", codeLabel: "Equatorial Guinea" },
            { codeValue: "GR", codeLabel: "Greece" },
            {
                codeValue: "GS",
                codeLabel: "South Georgia and the South Sandwich Islands"
            },
            { codeValue: "GT", codeLabel: "Guatemala" },
            { codeValue: "GU", codeLabel: "Guam" },
            { codeValue: "GW", codeLabel: "Guinea-Bissau" },
            { codeValue: "GY", codeLabel: "Guyana" },
            { codeValue: "HK", codeLabel: "Hong Kong" },
            { codeValue: "HM", codeLabel: "Heard Island and McDonald Islands" },
            { codeValue: "HN", codeLabel: "Honduras" },
            { codeValue: "HR", codeLabel: "Croatia" },
            { codeValue: "HT", codeLabel: "Haiti" },
            { codeValue: "HU", codeLabel: "Hungary" },
            { codeValue: "ID", codeLabel: "Indonesia" },
            { codeValue: "IE", codeLabel: "Ireland" },
            { codeValue: "IL", codeLabel: "Israel" },
            { codeValue: "IM", codeLabel: "Isle of Man" },
            { codeValue: "IN", codeLabel: "India" },
            { codeValue: "IO", codeLabel: "British Indian Ocean Territory" },
            { codeValue: "IQ", codeLabel: "Iraq" },
            { codeValue: "IR", codeLabel: "Iran (Islamic Republic of)" },
            { codeValue: "IS", codeLabel: "Iceland" },
            { codeValue: "IT", codeLabel: "Italy" },
            { codeValue: "JE", codeLabel: "Jersey" },
            { codeValue: "JM", codeLabel: "Jamaica" },
            { codeValue: "JO", codeLabel: "Jordan" },
            { codeValue: "JP", codeLabel: "Japan" },
            { codeValue: "KE", codeLabel: "Kenya" },
            { codeValue: "KG", codeLabel: "Kyrgyzstan" },
            { codeValue: "KH", codeLabel: "Cambodia" },
            { codeValue: "KI", codeLabel: "Kiribati" },
            { codeValue: "KM", codeLabel: "Comoros" },
            { codeValue: "KN", codeLabel: "Saint Kitts and Nevis" },
            {
                codeValue: "KP",
                codeLabel: "Korea (Democratic People's Republic of)"
            },
            { codeValue: "KR", codeLabel: "Korea (Republic of)" },
            { codeValue: "KW", codeLabel: "Kuwait" },
            { codeValue: "KY", codeLabel: "Cayman Islands" },
            { codeValue: "KZ", codeLabel: "Kazakhstan" },
            { codeValue: "LA", codeLabel: "Lao People's Democratic Republic" },
            { codeValue: "LB", codeLabel: "Lebanon" },
            { codeValue: "LC", codeLabel: "Saint Lucia" },
            { codeValue: "LI", codeLabel: "Liechtenstein" },
            { codeValue: "LK", codeLabel: "Sri Lanka" },
            { codeValue: "LR", codeLabel: "Liberia" },
            { codeValue: "LS", codeLabel: "Lesotho" },
            { codeValue: "LT", codeLabel: "Lithuania" },
            { codeValue: "LU", codeLabel: "Luxembourg" },
            { codeValue: "LV", codeLabel: "Latvia" },
            { codeValue: "LY", codeLabel: "Libya" },
            { codeValue: "MA", codeLabel: "Morocco" },
            { codeValue: "MC", codeLabel: "Monaco" },
            { codeValue: "MD", codeLabel: "Moldova (Republic of)" },
            { codeValue: "ME", codeLabel: "Montenegro" },
            { codeValue: "MF", codeLabel: "Saint Martin (French part)" },
            { codeValue: "MG", codeLabel: "Madagascar" },
            { codeValue: "MH", codeLabel: "Marshall Islands" },
            {
                codeValue: "MK",
                codeLabel: "Macedonia (the former Yugoslav Republic of)"
            },
            { codeValue: "ML", codeLabel: "Mali" },
            { codeValue: "MM", codeLabel: "Myanmar" },
            { codeValue: "MN", codeLabel: "Mongolia" },
            { codeValue: "MO", codeLabel: "Macao" },
            { codeValue: "MP", codeLabel: "Northern Mariana Islands" },
            { codeValue: "MQ", codeLabel: "Martinique" },
            { codeValue: "MR", codeLabel: "Mauritania" },
            { codeValue: "MS", codeLabel: "Montserrat" },
            { codeValue: "MT", codeLabel: "Malta" },
            { codeValue: "MU", codeLabel: "Mauritius" },
            { codeValue: "MV", codeLabel: "Maldives" },
            { codeValue: "MW", codeLabel: "Malawi" },
            { codeValue: "MX", codeLabel: "Mexico" },
            { codeValue: "MY", codeLabel: "Malaysia" },
            { codeValue: "MZ", codeLabel: "Mozambique" },
            { codeValue: "NA", codeLabel: "Namibia" },
            { codeValue: "NC", codeLabel: "New Caledonia" },
            { codeValue: "NE", codeLabel: "Niger" },
            { codeValue: "NF", codeLabel: "Norfolk Island" },
            { codeValue: "NG", codeLabel: "Nigeria" },
            { codeValue: "NI", codeLabel: "Nicaragua" },
            { codeValue: "NL", codeLabel: "Netherlands" },
            { codeValue: "NO", codeLabel: "Norway" },
            { codeValue: "NP", codeLabel: "Nepal" },
            { codeValue: "NR", codeLabel: "Nauru" },
            { codeValue: "NU", codeLabel: "Niue" },
            { codeValue: "NZ", codeLabel: "New Zealand" },
            { codeValue: "OM", codeLabel: "Oman" },
            { codeValue: "PA", codeLabel: "Panama" },
            { codeValue: "PE", codeLabel: "Peru" },
            { codeValue: "PF", codeLabel: "French Polynesia" },
            { codeValue: "PG", codeLabel: "Papua New Guinea" },
            { codeValue: "PH", codeLabel: "Philippines" },
            { codeValue: "PK", codeLabel: "Pakistan" },
            { codeValue: "PL", codeLabel: "Poland" },
            { codeValue: "PM", codeLabel: "Saint Pierre and Miquelon" },
            { codeValue: "PN", codeLabel: "Pitcairn" },
            { codeValue: "PR", codeLabel: "Puerto Rico" },
            { codeValue: "PS", codeLabel: "Palestine, State of" },
            { codeValue: "PT", codeLabel: "Portugal" },
            { codeValue: "PW", codeLabel: "Palau" },
            { codeValue: "PY", codeLabel: "Paraguay" },
            { codeValue: "QA", codeLabel: "Qatar" },
            { codeValue: "RE", codeLabel: "Reunion" },
            { codeValue: "RO", codeLabel: "Romania" },
            { codeValue: "RS", codeLabel: "Serbia" },
            { codeValue: "RU", codeLabel: "Russian Federation" },
            { codeValue: "RW", codeLabel: "Rwanda" },
            { codeValue: "SA", codeLabel: "Saudi Arabia" },
            { codeValue: "SB", codeLabel: "Solomon Islands" },
            { codeValue: "SC", codeLabel: "Seychelles" },
            { codeValue: "SD", codeLabel: "Sudan" },
            { codeValue: "SE", codeLabel: "Sweden" },
            { codeValue: "SG", codeLabel: "Singapore" },
            {
                codeValue: "SH",
                codeLabel: "Saint Helena, Ascension and Tristan da Cunha"
            },
            { codeValue: "SI", codeLabel: "Slovenia" },
            { codeValue: "SJ", codeLabel: "Svalbard and Jan Mayen" },
            { codeValue: "SK", codeLabel: "Slovakia" },
            { codeValue: "SL", codeLabel: "Sierra Leone" },
            { codeValue: "SM", codeLabel: "San Marino" },
            { codeValue: "SN", codeLabel: "Senegal" },
            { codeValue: "SO", codeLabel: "Somalia" },
            { codeValue: "SR", codeLabel: "Suriname" },
            { codeValue: "SS", codeLabel: "South Sudan" },
            { codeValue: "ST", codeLabel: "Sao Tome and Principe" },
            { codeValue: "SV", codeLabel: "El Salvador" },
            { codeValue: "SX", codeLabel: "Sint Maarten (Dutch part)" },
            { codeValue: "SY", codeLabel: "Syrian Arab Republic" },
            { codeValue: "SZ", codeLabel: "Swaziland" },
            { codeValue: "TC", codeLabel: "Turks and Caicos Islands" },
            { codeValue: "TD", codeLabel: "Chad" },
            { codeValue: "TF", codeLabel: "French Southern Territories" },
            { codeValue: "TG", codeLabel: "Togo" },
            { codeValue: "TH", codeLabel: "Thailand" },
            { codeValue: "TJ", codeLabel: "Tajikistan" },
            { codeValue: "TK", codeLabel: "Tokelau" },
            { codeValue: "TL", codeLabel: "Timor-Leste" },
            { codeValue: "TM", codeLabel: "Turkmenistan" },
            { codeValue: "TN", codeLabel: "Tunisia" },
            { codeValue: "TO", codeLabel: "Tonga" },
            { codeValue: "TR", codeLabel: "Turkey" },
            { codeValue: "TT", codeLabel: "Trinidad and Tobago" },
            { codeValue: "TV", codeLabel: "Tuvalu" },
            { codeValue: "TW", codeLabel: "Taiwan, Province of China[a]" },
            { codeValue: "TZ", codeLabel: "Tanzania, United Republic of" },
            { codeValue: "UA", codeLabel: "Ukraine" },
            { codeValue: "UG", codeLabel: "Uganda" },
            {
                codeValue: "UM",
                codeLabel: "United States Minor Outlying Islands"
            },
            { codeValue: "US", codeLabel: "United States of America" },
            { codeValue: "UY", codeLabel: "Uruguay" },
            { codeValue: "UZ", codeLabel: "Uzbekistan" },
            { codeValue: "VA", codeLabel: "Holy See" },
            { codeValue: "VC", codeLabel: "Saint Vincent and the Grenadines" },
            {
                codeValue: "VE",
                codeLabel: "Venezuela (Bolivarian Republic of)"
            },
            { codeValue: "VG", codeLabel: "Virgin Islands (British)" },
            { codeValue: "VI", codeLabel: "Virgin Islands (U.S.)" },
            { codeValue: "VN", codeLabel: "Viet Nam" },
            { codeValue: "VU", codeLabel: "Vanuatu" },
            { codeValue: "WF", codeLabel: "Wallis and Futuna" },
            { codeValue: "WS", codeLabel: "Samoa" },
            { codeValue: "YE", codeLabel: "Yemen" },
            { codeValue: "YT", codeLabel: "Mayotte" },
            { codeValue: "ZA", codeLabel: "South Africa" },
            { codeValue: "ZM", codeLabel: "Zambia" },
            { codeValue: "ZW", codeLabel: "Zimbabwe" }
        ],
        nullFlavorList: [
            { codeValue: "[[ASKU]]", codeLabel: "Asked But Unknown" },
            { codeValue: "[[NASK]]", codeLabel: "Not Asked" }
        ]
    },
    {
        itemId: "STD_REG_NO",
        itemLabel: "研究注册编号",
        elementId: "C.5.1.r.1",
        notation: "",
        uiType: "TEXT_INPUT",
        dataType: "AN",
        maxLength: "50",
        card: "0..1",
        dataLimit: "",
        dataSource: "",
        codeList: null,
        nullFlavorList: [
            { codeValue: "[[ASKU]]", codeLabel: "Asked But Unknown" },
            { codeValue: "[[NASK]]", codeLabel: "Not Asked" }
        ]
    },
    {
        itemId: "STD_SPN_NO",
        itemLabel: "申办者研究编号",
        elementId: "C.5.3",
        notation: "",
        uiType: "TEXT_INPUT",
        dataType: "AN",
        maxLength: "50",
        card: "0..1",
        dataLimit: "",
        dataSource: "",
        codeList: null,
        nullFlavorList: [
            { codeValue: "[[ASKU]]", codeLabel: "Asked But Unknown" },
            { codeValue: "[[NASK]]", codeLabel: "Not Asked" }
        ]
    }
];
export default itemList;